Repository AY2223S2-CS2113-T15-4/tp, pull requests merged in 2023-03, with the labels that each got.

#15 Reformat all Java source files according to style guide
  .gitignore
  src/main/java/Main.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/UnknownCommand.java
  src/main/java/objects/FlashcardList.java
  src/main/java/objects/exceptions/EmptyFlashcardAnswerException.java
  src/main/java/objects/exceptions/EmptyFlashcardQuestionException.java
  src/main/java/objects/exceptions/InvalidAddFlashcardInputException.java
  src/main/java/objects/flashcard/Flashcard.java
  src/main/java/parser/Parser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/ui/Ui.java
  src/test/java/objects/flashcard/FlashcardTest.java
  src/test/java/parser/ParserTest.java
Labels: type.Task, priority.High

#17 Set up Clanki for use with Gradle
  build.gradle
  src/main/java/com/clanki/Clanki.java
  src/main/java/com/clanki/commands/AddCommand.java
  src/main/java/com/clanki/commands/Command.java
  src/main/java/com/clanki/commands/UnknownCommand.java
  src/main/java/com/clanki/objects/FlashcardList.java
  src/main/java/com/clanki/objects/exceptions/EmptyFlashcardAnswerException.java
  src/main/java/com/clanki/objects/exceptions/EmptyFlashcardQuestionException.java
  src/main/java/com/clanki/objects/exceptions/InvalidAddFlashcardInputException.java
  src/main/java/com/clanki/objects/flashcard/Flashcard.java
  src/main/java/com/clanki/parser/Parser.java
  src/main/java/com/clanki/ui/Ui.java
  src/main/java/seedu/duke/Duke.java
  src/test/java/com/clanki/objects/flashcard/FlashcardTest.java
  src/test/java/com/clanki/parser/ParserTest.java
  src/test/java/seedu/duke/DukeTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#19 Enhance the Flashcard class
  src/main/java/com/clanki/exceptions/EmptyFlashcardAnswerException.java
  src/main/java/com/clanki/exceptions/EmptyFlashcardQuestionException.java
  src/main/java/com/clanki/exceptions/InvalidAddFlashcardInputException.java
  src/main/java/com/clanki/objects/Flashcard.java
  src/main/java/com/clanki/objects/FlashcardList.java
  src/main/java/com/clanki/objects/flashcard/Flashcard.java
  src/main/java/com/clanki/parser/Parser.java
  src/test/java/com/clanki/objects/FlashcardTest.java
  src/test/java/com/clanki/objects/flashcard/FlashcardTest.java
  src/test/java/com/clanki/parser/ParserTest.java
Labels: type.Story, priority.High

#22 Implement infinite loop to ask for user input until 'bye'
  src/main/java/com/clanki/Clanki.java
  src/main/java/com/clanki/commands/AddCommand.java
  src/main/java/com/clanki/commands/ByeCommand.java
  src/main/java/com/clanki/parser/Parser.java
  src/main/java/com/clanki/ui/Ui.java
  src/test/java/com/clanki/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#24 Fix check style warning due to constant not marked as static
  src/main/java/com/clanki/objects/Flashcard.java
Labels: type.Task, priority.Low

#25 Fix bug for add command caused by switching sequence of /q and /a
  src/main/java/com/clanki/parser/Parser.java
  src/test/java/com/clanki/parser/ParserTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#30 Add function of reviewing flashcards
  src/main/java/com/clanki/Clanki.java
  src/main/java/com/clanki/commands/Command.java
  src/main/java/com/clanki/commands/ReviewCommand.java
  src/main/java/com/clanki/commands/UnknownCommand.java
  src/main/java/com/clanki/objects/Flashcard.java
  src/main/java/com/clanki/objects/FlashcardList.java
  src/main/java/com/clanki/parser/Parser.java
  src/main/java/com/clanki/ui/Ui.java
  src/test/java/com/clanki/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.bat
Labels: type.Story, priority.High

#29 Resize all pictures in AboutUs.md to 100x100
  docs/AboutUs.md
Labels: type.Task, priority.Low

#34 Include a welcome message that will be printed when starting
  src/main/java/com/clanki/Clanki.java
  src/main/java/com/clanki/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#27 Implement a more robust parser
  src/main/java/com/clanki/Clanki.java
  src/main/java/com/clanki/commands/DeleteCommand.java
  src/main/java/com/clanki/commands/UpdateCommand.java
  src/main/java/com/clanki/parser/ParsedInput.java
  src/main/java/com/clanki/parser/Parser.java
  src/main/java/com/clanki/ui/Ui.java
  src/test/java/com/clanki/parser/ParsedInputTest.java
  src/test/java/com/clanki/parser/ParserTest.java
Labels: type.Task, priority.Medium

#36 Enable assertions during run task
  build.gradle
Labels: type.Task, priority.Medium

#37 Include some assertion for AddCommand and Parser
  src/main/java/com/clanki/commands/AddCommand.java
  src/main/java/com/clanki/parser/Parser.java
Labels: type.Enhancement, severity.Low

#38 Update code to include logging inside code
  src/main/java/com/clanki/commands/AddCommand.java
  src/main/java/com/clanki/parser/Parser.java
Labels: severity.VeryLow

#46 Add storage system
  src/main/java/com/clanki/Clanki.java
  src/main/java/com/clanki/exceptions/InvalidStorageFilePathException.java
  src/main/java/com/clanki/exceptions/StorageOperationException.java
  src/main/java/com/clanki/objects/FlashcardList.java
  src/main/java/com/clanki/storage/FlashcardListDecoder.java
  src/main/java/com/clanki/storage/FlashcardListEncoder.java
  src/main/java/com/clanki/storage/StorageFile.java
  src/test/java/com/clanki/storage/FlashcardListDecoderTest.java
  src/test/java/com/clanki/storage/FlashcardListEncoderTest.java
Labels: type.Story, priority.High

#49 Add user guide
  docs/UserGuide.md
Labels: type.Task, priority.High

#51 Enhance storage system
  docs/UserGuide.md
  src/main/java/com/clanki/storage/FlashcardListDecoder.java
  src/main/java/com/clanki/storage/StorageFile.java
  src/test/java/com/clanki/storage/FlashcardListDecoderTest.java
Labels: type.Enhancement, priority.High
